kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dataplane-ansible-logs
  namespace: openstack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: dataplane-ansible-logs
  storageClasseName: local-storage
  volumeMode: Filesystem
